spring:
  application:
    name: profile-service
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: false
  datasource:
    url: jdbc:mysql://localhost:3306/profile
    username: root
    password: 12342
  data:
    mongodb:
      uri: mongodb://localhost:27017/profile_service?authSource=admin
      auto-index-creation: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:  
    bootstrap-servers: localhost:9092
    consumer:
      group-id: profile-service-group
      auto-offset-reset: earliest

server:
  port: 0
  shutdown: graceful

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}